.TH NUMBATUI_INDEXER 1 "2026-06-04" "NumbatUI" "User Commands"
.SH NAME
numbatui_indexer \- indexing helper for NumbatUI
.SH SYNOPSIS
.B numbatui_indexer
.I process-id instance-uuid app-path user-data-path
.RI [ log-file ]
.SH DESCRIPTION
.B numbatui_indexer
is the worker process used by
.BR NumbatUI (1)
to index source projects. It is normally launched automatically by the
graphical application and is not intended to be invoked directly by users.
.SH SEE ALSO
.BR NumbatUI (1)
.PP
Project home page: <https://github.com/quarkslab/NumbatUI>.
